version: "3.3"

services:
   mysql:
      image: mysql:5.7-oracle
      restart: always
      tty: true
      ports:
         - 3306:3306
      environment:
         MYSQL_DATABASE: mysqljs
         MYSQL_ROOT_PASSWORD: root